cassandra:
  image: "cassandra:latest"
  environment:
      - CASSANDRA_START_RPC="true"
  ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"

     