version: "3"

services:
  electrode_ota:
    image: "com.eteraiton.ota:latest"
    links:
        - cassandra:cassandra
    ports:
       - "9001:9001"
  
  cassandra:
    image: "cassandra:latest"
    environment:
        - CASSANDRA_START_RPC="true"
    ports:
        - "7000:7000"
        - "7001:7001"
        - "7199:7199"
        - "9042:9042"
        - "9160:9160"
    volumes:
        - cassandra:/var/lib/cassandra
 
volumes:
  cassandra:

     